<!--html head部分  通过引入文件完成(分别适应于PC和手机)-->
<?php include($plume['ROOT_PATH'] . "modules/Cms/View/layout/layoutP.phtml"); ?>

<link rel="stylesheet" href="/css/h5/h5.css">
<!--html body部分 开始-->
<div class="container">
	<div class="design-container">
		This h5 design container!!!
	</div>
</div>
<!--html body部分 结束-->

<!--html foot部分  通过引入文件完成-->
<?php include($plume['ROOT_PATH'] . "modules/Cms/View/layout/footer.phtml"); ?>